# Generated by Django 5.1.4 on 2025-01-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_created_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='کد دانشچویی', max_length=15, null=True),
        ),
    ]
