# Generated by Django 5.1.4 on 2025-01-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('form', 'student_id'), ('form', 'time_slot')},
        ),
    ]
