# Generated by Django 5.1.4 on 2025-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_course_name_form_professor_name_form_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='valid_student_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
