# Generated by Django 5.1.4 on 2025-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='valid_student_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
