# Generated by Django 5.1.4 on 2025-01-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_form_course_name_alter_form_professor_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('form', 'student_id'), ('form', 'time_slot')},
        ),
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('email', 'time_slot'), ('form', 'student_id'), ('form', 'time_slot')},
        ),
    ]
