# Generated by Django 5.1.4 on 2025-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_form_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='short_url',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
