# Generated by Django 5.1.4 on 2025-05-27 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_form_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='form',
            name='year',
            field=models.PositiveIntegerField(help_text='سال تحصیلی (مثلا: ۱۴۰۳)', validators=[django.core.validators.MinValueValidator(1404)]),
        ),
    ]
