# Generated by Django 5.1.4 on 2025-06-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_form_options_alter_form_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='google_meet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
