# Generated by Django 5.1.4 on 2025-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='model_instance_id',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
